# Generated by Django 4.2.4 on 2023-08-31 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderplaced',
            options={'verbose_name_plural': 'Orders Placed'},
        ),
    ]
